[[local|localrc]]
GIT_BASE=http://git.openstack.org
DEST=/opt/stack

LOGFILE=$DEST/logs/stack.sh.log
VERBOSE=True
SCREEN_LOGDIR=$DEST/logs/screen
OFFLINE=False

HOST_IP=10.10.0.219
PUBLIC_INTERFACE=ens4
TUNNEL_ENDPOINT_IP=10.10.1.219

ADMIN_PASSWORD=welcome123
MYSQL_PASSWORD=welcome123
RABBIT_PASSWORD=welcome123
SERVICE_PASSWORD=welcome123
SERVICE_TOKEN=welcome123
PLACEMENT_PASS=welcome123

ENABLED_SERVICES=n-cpu,neutron,q-agt
disable_service tempest
disable_service n-net

#ml2
Q_PLUGIN=ml2
Q_AGENT=openvswitch

# vxlan
Q_ML2_TENANT_NETWORK_TYPE=vxlan

FLOATING_RANGE=172.16.1.0/24
Q_FLOATING_ALLOCATION_POOL=start=172.16.1.50,end=172.16.1.99
PUBLIC_NETWORK_GATEWAY=172.16.1.1 
FIXED_RANGE=10.0.0.0/24
NETWORK_GATEWAY=10.0.0.1

SERVICE_HOST=10.10.0.220
RABBIT_HOST=$SERVICE_HOST
Q_HOST=$SERVICE_HOST
REMOTE_DB_IP=$SERVICE_HOST

# Make VNC work on compute node
NOVA_VNC_ENABLED=True
NOVNCPROXY_URL=http://$SERVICE_HOST:6080/vnc_auto.html
VNCSERVER_LISTEN=$HOST_IP
VNCSERVER_PROXYCLIENT_ADDRESS=$VNCSERVER_LISTEN

[[post-config|$NOVA_CONF]]
[placement]
os_region_name = RegionOne
project_domain_name = Default
project_name = service
auth_type = password
user_domain_name = Default
auth_url = http://$SERVICE_HOST:35357/v3
username = placement
password = $PLACEMENT_PASS
